### ISSUE TITLE
[backend] AWS LightSail 서버에서 해군 사이트 request시 에러 

### ISSUE THREAD

**Issue by jiwonMe** [jiwonMe/rokn-letter#3]
네이버는 되는데 해군 사이트만 에러 발생
```
(django) ubuntu@ip-172-26-4-77:~/workspace/rokn-letter$ python
Python 3.9.5 (default, May 19 2021, 11:32:47) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> s = requests.Session()
>>> req = s.get('https://naver.com')
>>> req
<Response [200]>
>>> req = s.get('https://www.edunavy.mil.kr:10003/themes/basic/sub2/4_5.jsp', verify=False)
Traceback (most recent call last):
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa27a5414f0>: Failed to establish a new connection: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.edunavy.mil.kr', port=10003): Max retries exceeded with url: /themes/basic/sub2/4_5.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa27a5414f0>: Failed to establish a new connection: [Errno 110] Connection timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/venvs/django/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.edunavy.mil.kr', port=10003): Max retries exceeded with url: /themes/basic/sub2/4_5.jsp (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa27a5414f0>: Failed to establish a new connection: [Errno 110] Connection timed out'))
```

**Comment by jiwonMe** [comment]
집에서 traceout 실행시
```
traceroute edunavy.mil.kr
traceroute to edunavy.mil.kr (211.236.124.68), 64 hops max, 52 byte packets
 1  192.168.0.1 (192.168.0.1)  6.753 ms  2.172 ms  2.466 ms
 2  180.67.132.1 (180.67.132.1)  7.199 ms  4.146 ms  3.418 ms
 3  100.67.93.201 (100.67.93.201)  3.012 ms  3.056 ms  2.868 ms
 4  100.67.26.125 (100.67.26.125)  1.655 ms  1.933 ms  1.922 ms
 5  10.70.252.0 (10.70.252.0)  1.691 ms  2.002 ms  1.824 ms
 6  10.222.8.88 (10.222.8.88)  6.221 ms
    10.222.8.76 (10.222.8.76)  7.700 ms
    10.222.8.88 (10.222.8.88)  4.490 ms
 7  175.124.53.117 (175.124.53.117)  3.922 ms
    118.221.5.114 (118.221.5.114)  29.211 ms
    175.124.53.117 (175.124.53.117)  2.704 ms
 8  222.233.213.234 (222.233.213.234)  3.050 ms  5.962 ms  3.714 ms
 9  * * *
10  * * *
11  * * *
12  211.255.110.6 (211.255.110.6)  3.888 ms  3.301 ms  3.188 ms
13  211.255.110.18 (211.255.110.18)  3.380 ms  4.603 ms  3.510 ms
14  211.255.120.14 (211.255.120.14)  6.881 ms  7.889 ms  8.048 ms
15  * * *
16  * * *
```

LightSail에서 실행시
```
traceroute edunavy.mil.kr -m 60
traceroute to edunavy.mil.kr (211.236.124.68), 60 hops max, 60 byte packets
 1  ec2-52-79-0-135.ap-northeast-2.compute.amazonaws.com (52.79.0.135)  5.408 ms ec2-52-79-0-137.ap-northeast-2.compute.amazonaws.com (52.79.0.137)  0.837 ms ec2-52-79-0-147.ap-northeast-2.compute.amazonaws.com (52.79.0.147)  1.787 ms
 2  100.65.18.128 (100.65.18.128)  1.921 ms 100.65.19.128 (100.65.19.128)  1.810 ms 100.65.18.48 (100.65.18.48)  5.305 ms
 3  100.66.8.176 (100.66.8.176)  6.728 ms 100.66.8.172 (100.66.8.172)  6.036 ms 100.66.8.212 (100.66.8.212)  3.383 ms
 4  100.66.10.0 (100.66.10.0)  3.403 ms 100.66.10.98 (100.66.10.98)  8.550 ms 100.66.11.98 (100.66.11.98)  4.674 ms
 5  100.66.7.39 (100.66.7.39)  2.293 ms * 100.66.6.99 (100.66.6.99)  10.758 ms
 6  100.66.4.107 (100.66.4.107)  7.170 ms 100.66.4.101 (100.66.4.101)  6.495 ms 100.66.4.169 (100.66.4.169)  2.043 ms
 7  100.65.9.193 (100.65.9.193)  0.268 ms 100.65.11.193 (100.65.11.193)  0.714 ms 100.65.8.97 (100.65.8.97)  4.803 ms
 8  52.93.247.3 (52.93.247.3)  5.512 ms 52.93.247.7 (52.93.247.7)  5.070 ms 52.93.247.3 (52.93.247.3)  5.632 ms
 9  54.239.123.50 (54.239.123.50)  1.888 ms  2.128 ms 54.239.123.28 (54.239.123.28)  2.612 ms
10  54.239.123.123 (54.239.123.123)  1.147 ms  1.257 ms 54.239.123.59 (54.239.123.59)  2.216 ms
11  211.60.104.21 (211.60.104.21)  0.911 ms 211.60.104.9 (211.60.104.9)  0.751 ms 211.60.104.21 (211.60.104.21)  0.904 ms
12  1.213.144.21 (1.213.144.21)  7.137 ms 1.213.150.109 (1.213.150.109)  4.705 ms 1.213.146.97 (1.213.146.97)  1.230 ms
13  * 1.208.173.106 (1.208.173.106)  1.075 ms *
14  * * 210.107.53.198 (210.107.53.198)  2.099 ms
15  * * *
16  * * *
17  * 211.255.110.10 (211.255.110.10)  2.324 ms  2.181 ms
18  211.255.110.2 (211.255.110.2)  2.984 ms  3.054 ms  2.927 ms
19  211.255.110.10 (211.255.110.10)  2.613 ms *  2.416 ms
20  211.255.120.14 (211.255.120.14)  4.517 ms * *
21  * * *
```

**Comment by jiwonMe** [comment]
## NCP(Naver Cloud Platform) 사용시 됨

```
>>> url = "https://www.edunavy.mil.kr:10003"
>>> s.get(url)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 852, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 340, in connect
    ssl_context=context)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 332, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.edunavy.mil.kr', port=10003): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 520, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 630, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.edunavy.mil.kr', port=10003): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
>>> s.get(url, verify=False)
/usr/lib/python3/dist-packages/urllib3/connectionpool.py:860: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
<Response [200]>
```

**Comment by jiwonMe** [comment]
NCP 속도가 느려 GCP로 서버 이전
